/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TokenizedProfileLauncherInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "defaultLockingPeriod"
      | "deployToken"
      | "generateSalt"
      | "initialSwapTokens"
      | "liquidityLocker"
      | "lpFeesCut"
      | "owner"
      | "positionManager"
      | "predictTokenAddress"
      | "protocolCut"
      | "renounceOwnership"
      | "swapRouter"
      | "taxCollector"
      | "transferOwnership"
      | "uniswapV3Factory"
      | "updateLiquidityLocker"
      | "weth"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DebugAddress"
      | "DebugIntValues"
      | "DebugStep"
      | "DebugValues"
      | "OwnershipTransferred"
      | "TokenCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "defaultLockingPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployToken",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "generateSalt",
    values: [AddressLike, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialSwapTokens",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidityLocker",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lpFeesCut", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positionManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "predictTokenAddress",
    values: [AddressLike, string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolCut",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "taxCollector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapV3Factory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateLiquidityLocker",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "weth", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "defaultLockingPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generateSalt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialSwapTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidityLocker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lpFeesCut", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "positionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "predictTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolCut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapRouter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "taxCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapV3Factory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLiquidityLocker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "weth", data: BytesLike): Result;
}

export namespace DebugAddressEvent {
  export type InputTuple = [name: string, addr: AddressLike];
  export type OutputTuple = [name: string, addr: string];
  export interface OutputObject {
    name: string;
    addr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugIntValuesEvent {
  export type InputTuple = [name: string, value: BigNumberish];
  export type OutputTuple = [name: string, value: bigint];
  export interface OutputObject {
    name: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugStepEvent {
  export type InputTuple = [step: string];
  export type OutputTuple = [step: string];
  export interface OutputObject {
    step: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugValuesEvent {
  export type InputTuple = [name: string, value: BigNumberish];
  export type OutputTuple = [name: string, value: bigint];
  export interface OutputObject {
    name: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenCreatedEvent {
  export type InputTuple = [
    tokenAddress: AddressLike,
    lpNftId: BigNumberish,
    deployer: AddressLike,
    name: string,
    symbol: string,
    supply: BigNumberish,
    recipient: AddressLike,
    recipientAmount: BigNumberish
  ];
  export type OutputTuple = [
    tokenAddress: string,
    lpNftId: bigint,
    deployer: string,
    name: string,
    symbol: string,
    supply: bigint,
    recipient: string,
    recipientAmount: bigint
  ];
  export interface OutputObject {
    tokenAddress: string;
    lpNftId: bigint;
    deployer: string;
    name: string;
    symbol: string;
    supply: bigint;
    recipient: string;
    recipientAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TokenizedProfileLauncher extends BaseContract {
  connect(runner?: ContractRunner | null): TokenizedProfileLauncher;
  waitForDeployment(): Promise<this>;

  interface: TokenizedProfileLauncherInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  defaultLockingPeriod: TypedContractMethod<[], [bigint], "view">;

  deployToken: TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _supply: BigNumberish,
      _initialTick: BigNumberish,
      _fee: BigNumberish,
      _salt: BytesLike,
      _deployer: AddressLike,
      _recipient: AddressLike,
      _recipientAmount: BigNumberish
    ],
    [[string, bigint] & { tokenAddress: string; tokenId: bigint }],
    "payable"
  >;

  generateSalt: TypedContractMethod<
    [deployer: AddressLike, name: string, symbol: string, supply: BigNumberish],
    [[string, string] & { salt: string; token: string }],
    "view"
  >;

  initialSwapTokens: TypedContractMethod<
    [token: AddressLike, _fee: BigNumberish],
    [void],
    "payable"
  >;

  liquidityLocker: TypedContractMethod<[], [string], "view">;

  lpFeesCut: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  positionManager: TypedContractMethod<[], [string], "view">;

  predictTokenAddress: TypedContractMethod<
    [
      deployer: AddressLike,
      name: string,
      symbol: string,
      supply: BigNumberish,
      salt: BytesLike
    ],
    [string],
    "view"
  >;

  protocolCut: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  swapRouter: TypedContractMethod<[], [string], "view">;

  taxCollector: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  uniswapV3Factory: TypedContractMethod<[], [string], "view">;

  updateLiquidityLocker: TypedContractMethod<
    [newLocker: AddressLike],
    [void],
    "nonpayable"
  >;

  weth: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "defaultLockingPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deployToken"
  ): TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _supply: BigNumberish,
      _initialTick: BigNumberish,
      _fee: BigNumberish,
      _salt: BytesLike,
      _deployer: AddressLike,
      _recipient: AddressLike,
      _recipientAmount: BigNumberish
    ],
    [[string, bigint] & { tokenAddress: string; tokenId: bigint }],
    "payable"
  >;
  getFunction(
    nameOrSignature: "generateSalt"
  ): TypedContractMethod<
    [deployer: AddressLike, name: string, symbol: string, supply: BigNumberish],
    [[string, string] & { salt: string; token: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialSwapTokens"
  ): TypedContractMethod<
    [token: AddressLike, _fee: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "liquidityLocker"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lpFeesCut"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "positionManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "predictTokenAddress"
  ): TypedContractMethod<
    [
      deployer: AddressLike,
      name: string,
      symbol: string,
      supply: BigNumberish,
      salt: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolCut"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "swapRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "taxCollector"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "uniswapV3Factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateLiquidityLocker"
  ): TypedContractMethod<[newLocker: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "weth"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "DebugAddress"
  ): TypedContractEvent<
    DebugAddressEvent.InputTuple,
    DebugAddressEvent.OutputTuple,
    DebugAddressEvent.OutputObject
  >;
  getEvent(
    key: "DebugIntValues"
  ): TypedContractEvent<
    DebugIntValuesEvent.InputTuple,
    DebugIntValuesEvent.OutputTuple,
    DebugIntValuesEvent.OutputObject
  >;
  getEvent(
    key: "DebugStep"
  ): TypedContractEvent<
    DebugStepEvent.InputTuple,
    DebugStepEvent.OutputTuple,
    DebugStepEvent.OutputObject
  >;
  getEvent(
    key: "DebugValues"
  ): TypedContractEvent<
    DebugValuesEvent.InputTuple,
    DebugValuesEvent.OutputTuple,
    DebugValuesEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokenCreated"
  ): TypedContractEvent<
    TokenCreatedEvent.InputTuple,
    TokenCreatedEvent.OutputTuple,
    TokenCreatedEvent.OutputObject
  >;

  filters: {
    "DebugAddress(string,address)": TypedContractEvent<
      DebugAddressEvent.InputTuple,
      DebugAddressEvent.OutputTuple,
      DebugAddressEvent.OutputObject
    >;
    DebugAddress: TypedContractEvent<
      DebugAddressEvent.InputTuple,
      DebugAddressEvent.OutputTuple,
      DebugAddressEvent.OutputObject
    >;

    "DebugIntValues(string,int256)": TypedContractEvent<
      DebugIntValuesEvent.InputTuple,
      DebugIntValuesEvent.OutputTuple,
      DebugIntValuesEvent.OutputObject
    >;
    DebugIntValues: TypedContractEvent<
      DebugIntValuesEvent.InputTuple,
      DebugIntValuesEvent.OutputTuple,
      DebugIntValuesEvent.OutputObject
    >;

    "DebugStep(string)": TypedContractEvent<
      DebugStepEvent.InputTuple,
      DebugStepEvent.OutputTuple,
      DebugStepEvent.OutputObject
    >;
    DebugStep: TypedContractEvent<
      DebugStepEvent.InputTuple,
      DebugStepEvent.OutputTuple,
      DebugStepEvent.OutputObject
    >;

    "DebugValues(string,uint256)": TypedContractEvent<
      DebugValuesEvent.InputTuple,
      DebugValuesEvent.OutputTuple,
      DebugValuesEvent.OutputObject
    >;
    DebugValues: TypedContractEvent<
      DebugValuesEvent.InputTuple,
      DebugValuesEvent.OutputTuple,
      DebugValuesEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokenCreated(address,uint256,address,string,string,uint256,address,uint256)": TypedContractEvent<
      TokenCreatedEvent.InputTuple,
      TokenCreatedEvent.OutputTuple,
      TokenCreatedEvent.OutputObject
    >;
    TokenCreated: TypedContractEvent<
      TokenCreatedEvent.InputTuple,
      TokenCreatedEvent.OutputTuple,
      TokenCreatedEvent.OutputObject
    >;
  };
}
