/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMultiPositionLiquidityLocker,
  IMultiPositionLiquidityLockerInterface,
} from "../../../contracts/interface.sol/IMultiPositionLiquidityLocker";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "unlockTime",
        type: "uint64",
      },
      {
        internalType: "uint16",
        name: "lpFeesCut",
        type: "uint16",
      },
    ],
    name: "initializePosition",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMultiPositionLiquidityLocker__factory {
  static readonly abi = _abi;
  static createInterface(): IMultiPositionLiquidityLockerInterface {
    return new Interface(_abi) as IMultiPositionLiquidityLockerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMultiPositionLiquidityLocker {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IMultiPositionLiquidityLocker;
  }
}
